# Generated by Django 5.0.1 on 2024-03-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(default='iiitd', max_length=100),
        ),
    ]
