# Generated by Django 5.0.1 on 2024-03-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0004_location_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
    ]
