# Generated by Django 5.0.1 on 2024-04-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0007_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='riss',
            field=models.CharField(default='-123', max_length=100),
        ),
    ]
