# Generated by Django 5.0.1 on 2024-04-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0009_riss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riss',
            old_name='riss',
            new_name='riss_message',
        ),
    ]
