# Generated by Django 5.0.1 on 2024-05-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0010_rename_riss_riss_riss_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='riss',
        ),
        migrations.AddField(
            model_name='location',
            name='identity',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='message',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='mode',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default='2021-09-01 00:00:00', max_length=100),
        ),
    ]
