# Generated by Django 5.0.1 on 2024-05-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0011_delete_riss_location_identity_location_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='riss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riss_message', models.CharField(max_length=100)),
                ('riss2', models.CharField(max_length=100)),
            ],
        ),
    ]
