# Generated by Django 5.0.1 on 2024-05-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0012_riss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riss',
            name='riss2',
        ),
    ]
