# Generated by Django 5.0.1 on 2024-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0013_remove_riss_riss2'),
    ]

    operations = [
        migrations.CreateModel(
            name='location2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
            ],
        ),
    ]
