# Generated by Django 5.0.1 on 2024-05-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0014_location2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.CharField(default='2021-09-01 00:00:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='location2',
            name='latitude',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='location2',
            name='longitude',
            field=models.CharField(default='-123', max_length=100),
        ),
    ]
