# Generated by Django 5.0.1 on 2024-05-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0015_alter_location_time_alter_location2_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='riss',
            new_name='Riss',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='time',
            new_name='Timed',
        ),
    ]
