# Generated by Django 5.1 on 2024-08-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0016_rename_riss_location_riss_rename_time_location_timed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Riss',
            field=models.CharField(default='00', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='Timed',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
